
spring:
  profiles:
    active: prod
  application:
    name: dig-event
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: abc123
  data:
    redis:
      host: localhost
      port: 6379
logging:
  config: classpath:logging/logback-spring.xml
#logging:
#  level:
#    root: info
#  file:
#    name: ${LOG_HOME}/%d{yyyyMMdd}/${APP_NAME}-%d{yyyyMMdd}-%i.log
#  logback:
#    rollingpolicy:
#      max-file-size: 1MB
#server:
#  servlet:
#    context-path: /aaa
#  port: 8083
mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名法和下划线之间的转换

#swagger配置
swagger:
  title: 大事件-文章管理系统
  version: v1.0.0
  description: 文章管理系统api
  security-schemes:
    - in: header
      type: apikey
      name: token
#springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: '大事件-文章'
      paths-to-match: '/**'
      packages-to-scan: com.wenjuju.top.controller # 设置包扫描路径

#knife4j增强配置
knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-version: true
    swagger-model-name: 实体类列表
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: 割爱之举
  basic:
    enable: true  #生产环境关闭
    username: yyt
    password: yyt_123


#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    tags-sorter: alpha
#    operations-sorter: alpha
#  api-docs:
#    path: /v3/api-docs
#  group-configs:
#    - group: 'default'
#      paths-to-match: '/**'
#      packages-to-scan: com.xiaominfo.knife4j.demo.web
## knife4j的增强配置，不需要增强可以不配
#knife4j:
#  enable: true
#  setting:
#    language: zh_cn